services:
   app:
      build:
         context: .
         dockerfile: Dockerfile
         target: development
      environment:
         - MONGODB_URI=${MONGODB_URI}
         - PORT = ${PORT}
         - JWT_SECRET=${JWT_SECRET}
      volumes:
         - ./:/usr/src/app
         - /usr/src/app/node_modules
      ports:
         - '3000:3000'
      depends_on:
         - redis
   redis:
      image: redis/redis-stack:latest
      container_name: redis-stack
      ports:
         - '6379:6379'
         - '8001:8001'
      volumes:
         - redis-stack-data:/redis     

volumes:
  redis-stack-data: